### ISSUE TITLE
correlate_data returning empty dataframe

### ISSUE THREAD

**Issue by callummole** [samtuhka/offline_surface_gaze#1]
Hi Sam, (thought I'd use github rather than clogging up your junk email!)

Even with a redefined surface on the corrected video file, I was still having problems using your code to export normalised gaze positions. 

I've chased the problem down to the correlate_data function in main.py returning an empty dataframe. This is because I sync timestamp using pupil-remote with the experiment PC and the eyetracking laptop in the Lab at the start of every trial. There seems to be a small delay in syncing the gaze position timestamps with the world timestamps, so that the first recording gaze positions have a high timestamp (higher than the trial length). 

Since you only iterate through the timestamp depending on whether the gaze timestamp is less than the world timestamp, no gaze positions are recorded.

       if datum['timestamp'] <= ts:
            print ("matched timstamp")
            datum['index'] = frame_idx
            data_by_frame[frame_idx].append(datum)
            data_index +=1

I suggest adding the line:
data = sorted(data, key = lambda x: x['timestamp'])
before the while loop, to avoid this issue.

Thanks for all your help with this. I've finally got everything working. Are you happy for me to fork the repo and also gazesim_tools, so that people know they've come from your work when I link any publications through? 

Callum

**Comment by samtuhka** [comment]
Cool!

Feel free to fork anything. I might want get a fair warning so I can have an opportunity to clean up gazesim_tools a bit before it's linked to publicly, but it's fine either way. Also to be clear, a bunch of the stuff is just edited Pupil Labs code to suit my/our purposes better.

**Comment by samtuhka** [comment]
Made sure both timestamps are in order. 

I might want to figure out a better solution later. Now the data points before the change in timebase might sneak up somewhere they don't belong (if the change in timesbase is smaller than the recording length), but I assume it's just a few points and won't mess up things noticeably.

**Comment by callummole** [comment]
Yes, I gathered. But it's still a lot of work to understand the code enough to adapt it.


I'm getting inception style bugs within bugs, and still not completely out of the woods. I'll outline my issue below. This is FYI, I don't expect you to attempt to help solve it.


Analysis steps:

1) run extract_markers on one file with rewrite = True. This now works great after changing the video compression.

2) Open pupil-player.exe and add a new surface on the corrected world video. When you close pupil-player it saves a new surface_definitions file, move this file somewhere safe. This process also saves new square_marker_cache file (let's call this player_cache)

3) Run extract_markers again with rewrite = False, on all the desired folder directories to get corrected square_marker_cache files (let's call these corrected_cache).

4) Run main.py to output csv for normalised gaze on surface.


My issue is that when I use the player_cache then main.py produces lovely full csvs of sensible values.


However, when I use the corrected_cache then main.py doesn't recognise any gaze positions as being on the surface (m_from_screen is empty). CSVs are created, but are empty apart from the header row.


Even though it's my understanding that the functions involved in producing player_cache and corrected_cache are the same, correct? So I'm puzzled why the corrected_cache is different to the player_cache.


I suspect it may be because I'm analysing this on a windows PC which isn't set up as a pupil-labs developer PC (I don't have admin rights so cannot install drivers etc.), so maybe running the same functions outside of the .exe causes some silent failures (yet corrected_cache is not empty). I'll investigate on the linux laptop where I can run pupil-player from source.


Just keeping you updated since you're using the same code & solving similar problems. Let me know if you don't me filling up your inbox anymore.

Callum





________________________________

**Comment by samtuhka** [comment]
Oh... crap. The problem is probably that it actually tries to re-rectify the already rectified image again (it just doesn't write it). 

You can change the name of the the saved square_marker_cache (should be in extract_markers.py and main.py) so that pupil player doesn't overwrite it.

Eidt: No, that can't be it. Misread your post.

**Comment by callummole** [comment]
Sorry I don't think I was clear. The problem isn't that the marker cache gets overwritten, it's that main.py only recognises the gaze positions as on the surface if I recreate the marker cache through pupil_player, rather than using the cache produced by extract_markers.


Shouldn't extract_markers produce similar marker positions (corrected_cache) to recreating the marker cache through the player (player_cache)? Since they are calling the same functions?


It's not feasible for me to have to regenerate the square_marker_cache through pupil-player (i.e. create a player_cache) for every recording (since I have a recording for every trial).


________________________________

**Comment by samtuhka** [comment]
Yes, they should be the same. Are the corrected caches of relatively the same size as the player_caches?

**Comment by samtuhka** [comment]
You can send me an example corrected_cache and player_cache through email and I can have a look at it.

**Comment by callummole** [comment]
Done. The corrected_cache is typically a little larger than the player_cache. (e.g. 749KB vs 921KB)


________________________________
